site_name: Ethstaker Guides
#site_url: https://guides.ethstaker.cc  # Hoped-for CNAME in future
site_url: https://eth-educators.github.io/ethstaker-guides/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
nav:
  - Home: README.md
  - Better Router:
    - Overview: home-router/overview.md
    - Prepare: home-router/prepare.md
  - Holesky Testnet:
    - Lighthouse/Nethermind: holesky-node.md
    - Lodestar/Reth: holesky-node-alt.md
  - Monitoring and Maintenance:
    - Monitoring: monitoring.md
    - Alerting: alerting.md
    - Maintenance and Security: security-maintenance.md
    - Migrate to a larger disk: migrating-to-a-larger-disk.md
  - Exiting a validaror: voluntary-exit.md
  - MEV Relay List: MEV-relay-list.md
  - Legacy Guides:
    - Prepare for the Merge: prepare-for-the-merge.md
