site_name: Ethstaker Guides
site_url: https://guides.ethstaker.cc
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ethstaker
    - icon: fontawesome/brands/github
      link: https://github.com/eth-educators
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ethstaker
nav:
  - Home: README.md
  - Better Router:
    - Overview: home-router/overview.md
    - Prepare: home-router/prepare.md
    - Netgear Router Setup:
      - Initial Setup: home-router/rs300-start.md
      - Port Forwarding: home-router/rs300-advanced.md
    - Final Switchover:
      - Comcast: home-router/comcast-bridge.md
  - Holesky Testnet:
    - Lighthouse/Nethermind: holesky-node.md
    - Lodestar/Reth: holesky-node-alt.md
  - Monitoring and Maintenance:
    - Monitoring: monitoring.md
    - Alerting: alerting.md
    - Maintenance and Security: security-maintenance.md
    - Migrate to a larger disk: migrating-to-a-larger-disk.md
  - Exiting a validator: voluntary-exit.md
  - Legacy Guides:
    - Prepare for the Merge: prepare-for-the-merge.md
