site_name: Ethstaker Guides
site_url: https://guides.ethstaker.cc
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
nav:
  - Home: README.md
  - Better Router:
    - Overview: home-router/overview.md
